server:
  port: 8081

spring:
  application:
    name: api-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.137:3306/api_db?serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.5.137
    port: 6379
    password: 1234
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        time-between-eviction-runs: 10s

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MybatisPlus配置
mybatis-plus:
  type-aliases-package: com.zhenwu.api.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# dubbo配置
dubbo:
  application:
    name: dubbo-springboot-provider
  protocol:
    name: tri
    port: 50052
  registry:
    address: zookeeper://192.168.5.137:2181
    timeout: 60000
    parameters:
      blockUntilConnectedWait: 250