---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhenwu.
---

-- 1.参数列表
-- 1.1 用户token
local token = ARGV[1]
-- 1.2 用户账号
local userAccount = ARGV[2]

-- 2.数据key
-- 2.1 用户 token key
local tokenKey = 'login:token:' .. token
-- 2.1 用户 account key
local accountKey = 'login:online:' .. userAccount

-- 3.删除数据
redis.call('DEL', tokenKey)
redis.call('DEL', accountKey)

return 0