---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhenwu.
---
local userAccountArray = ARGV;
for i = 1, #userAccountArray do
    local accountKey = 'login:online:' .. userAccountArray[i];
    -- 判断该用户是否在线
    if (redis.call('EXISTS', accountKey) == 1) then
        -- 在线，删除token和在线用户
        local token = redis.call('GET', accountKey);
        local tokenKey = 'login:token:' .. token
        redis.call('DEL', tokenKey)
        redis.call('DEL', accountKey)
    end;
end;
return 0